version: '3'

services:
  # Сервис Django
  web:
    build: .
    command: gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8888  # изменен порт на 8888
    volumes:
      - .:/app
    ports:
      - "8888:8888"  # изменен порт на 8888
  
  # Сервис Nginx
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"  # изменен порт на 8888
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
