version: '3'

services:
  web:
    build: .
    command: gunicorn --config gunicorn_conf.py core.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
