version: '3'

services:
  web:
    build: .
    command: ["gunicorn", "core.wsgi:application", "-b", "0.0.0.0:8000"]
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
volumes:
  static:
  media:
