version: '3'

services:
  # Сервис Django
  web:
    build: .
    command: gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8889
    volumes:
      - .:/app
    ports:
      - "8889:8889"
  
  # Сервис Nginx
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
