version: '3'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
