version: '3'

services:
  web:
    build: .
    command: ["gunicorn", "core.wsgi:application", "-b", "0.0.0.0:8000"]
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:8000"  # изменение порта на 80
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy_params:/etc/nginx/proxy_params
    ports:
      - "8080:80"  # сохранение порта 8080 для доступа к Nginx в случае необходимости

volumes:
  static:
  media:
