version: "3"

services:

  autodocs_web:
    container_name: web_autodocs
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./media/:/media
      - ./static/:/static
      - ./:/app
    entrypoint: ./wsgi-entrypoint.sh
    restart: always

volumes:
  media:
  static:
