# Generated by Django 4.2.7 on 2023-11-27 12:25

from django.db import migrations, models
import django_countries.fields
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('for_whome', models.CharField(choices=[('Студентам', 'Студентам'), ('Взрослым', 'Взрослым'), ('Школьникам', 'Школьникам'), ('Детям', 'Детям')], max_length=255)),
                ('type_of_training', models.CharField(choices=[('Языковые курсы', 'Языковые курсы'), ('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура'), ('Средняя школа', 'Средняя школа'), ('Каникулы', 'Каникулы'), ('Дипломная программа', 'Дипломная программа'), ('Постдипломная программа', 'Постдипломная программа'), ('Сертификат', 'Сертификат')], max_length=255)),
                ('language', models.CharField(choices=[('Английский', 'Английский'), ('Немецкий', 'Немецкий'), ('Французский', 'Французский'), ('Китайский', 'Китайский'), ('Польский', 'Польский'), ('Чешский', 'Чешский'), ('Испанский', 'Испанский'), ('Русский', 'Русский'), ('Латышский', 'Латышский')], max_length=255)),
                ('accommodation', models.CharField(choices=[('В семье', 'В семье'), ('В общежитии', 'В общежитии'), ('В отеле', 'В отеле'), ('В пансионе', 'В пансионе'), ('В резиденции', 'В резиденции')], max_length=255)),
                ('price_kgs', models.FloatField(default=0)),
                ('price_usd', models.FloatField(default=0)),
                ('features_of_the_program', models.TextField(verbose_name='Особенности программы')),
                ('direction', models.TextField(verbose_name='Направление')),
                ('deadline_for_submission_of_documents', models.TextField(verbose_name='Дедлайн приема документов')),
                ('duration_of_the_program', models.TextField(verbose_name='Длительность программы')),
                ('description', django_quill.fields.QuillField()),
                ('document', models.FileField(upload_to='media/documents/')),
            ],
        ),
    ]
