# Generated by Django 4.2.7 on 2023-11-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyAbroad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyabroad',
            name='for_whome',
        ),
        migrations.AlterField(
            model_name='studyabroad',
            name='deadline_for_submission_of_documents',
            field=models.CharField(max_length=255, verbose_name='Дедлайн приема документов'),
        ),
        migrations.AlterField(
            model_name='studyabroad',
            name='duration_of_the_program',
            field=models.CharField(max_length=255, verbose_name='Длительность программы'),
        ),
        migrations.AlterField(
            model_name='studyabroad',
            name='features_of_the_program',
            field=models.CharField(max_length=255, verbose_name='Особенности программы'),
        ),
        migrations.CreateModel(
            name='StudyAbroadForWhome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_whome', models.CharField(choices=[('Студентам', 'Студентам'), ('Взрослым', 'Взрослым'), ('Школьникам', 'Школьникам'), ('Детям', 'Детям')], max_length=255)),
                ('study_abroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_whomes', to='studyAbroad.studyabroad')),
            ],
        ),
    ]
