# Generated by Django 4.2.7 on 2023-11-27 13:39

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studyAbroad', '0002_remove_studyabroad_for_whome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAbriadAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Программа', 'Программа'), ('Галерея', 'Галерея'), ('Требования', 'Требования'), ('Проживание', 'Проживание'), ('Цены и сроки', 'Цены и сроки')], max_length=355)),
                ('description', django_quill.fields.QuillField()),
                ('study_abroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='studyAbroad.studyabroad')),
            ],
        ),
    ]
