# Generated by Django 4.2.7 on 2023-12-01 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyAbroad', '0003_studyabriadadditional'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAbroadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('study_abroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyAbroad.studyabroad')),
            ],
        ),
    ]
