# Generated by Django 4.2.7 on 2023-12-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyAbroad', '0004_studyabroadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyabroad',
            name='name',
            field=models.CharField(default='hello', max_length=555),
            preserve_default=False,
        ),
    ]
