# Generated by Django 4.2.7 on 2023-12-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyAbroad', '0005_studyabroad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyabroadimage',
            name='study_abroad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='studyAbroad.studyabroad'),
        ),
    ]
