# Generated by Django 4.2.7 on 2023-12-08 11:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studyAbroad', '0006_alter_studyabroadimage_study_abroad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyabroad',
            name='country',
            field=django_countries.fields.CountryField(default='RU', max_length=2),
        ),
    ]
