# Generated by Django 4.2.7 on 2023-11-28 13:05

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesToComeFromAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='OpenVisaToGoAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Visas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555)),
                ('description', django_quill.fields.QuillField()),
            ],
        ),
    ]
