# Generated by Django 4.2.7 on 2023-12-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0002_visasimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisasImage',
        ),
    ]
