# Generated by Django 4.2.7 on 2023-11-27 05:31

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundsTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundsTourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('outbounds_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tours.outboundstour')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundsTourCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('outbounds_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='tours.outboundstour')),
            ],
        ),
    ]
