# Generated by Django 4.2.7 on 2023-11-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundstourday',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
