# Generated by Django 4.2.7 on 2023-11-27 05:51

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_outboundstour_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundstour',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='outboundstourday',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
