# Generated by Django 4.2.7 on 2023-11-27 07:13

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_outboundstour_inprice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundstour',
            name='amount_days',
            field=models.IntegerField(default=5, verbose_name='Количество дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundstour',
            name='amount_nights',
            field=models.IntegerField(default=6, verbose_name='Количество ночей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundstour',
            name='is_active_leisure',
            field=models.BooleanField(default=0, verbose_name='Активный отдых'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundstour',
            name='is_economy_tour',
            field=models.BooleanField(default=0, verbose_name='Экономичный тур'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundstour',
            name='is_holiday_tours',
            field=models.BooleanField(default=0, verbose_name='Туры на праздники'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundstour',
            name='is_last_minute_tours',
            field=models.BooleanField(default=0, verbose_name='Горящие туры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundstour',
            name='is_romantic_getaways',
            field=models.BooleanField(default=0, verbose_name='Романтический отдых'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundstour',
            name='is_sightseeing_tour',
            field=models.BooleanField(default=0, verbose_name='Экскурсионный тур'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outboundstour',
            name='description',
            field=django_quill.fields.QuillField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='outboundstour',
            name='inprice_description',
            field=django_quill.fields.QuillField(verbose_name='Условия тура'),
        ),
        migrations.AlterField(
            model_name='outboundstour',
            name='price_kgs',
            field=models.FloatField(default=0, verbose_name='Цена в долларах'),
        ),
        migrations.AlterField(
            model_name='outboundstour',
            name='price_usd',
            field=models.FloatField(default=0, verbose_name='Цена в сомах'),
        ),
    ]
