# Generated by Django 4.2.7 on 2023-11-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_outboundstour_amount_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundsTourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('outbounds_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.outboundstour')),
            ],
        ),
    ]
