# Generated by Django 4.2.7 on 2023-11-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_outboundstourimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundstour',
            name='description',
            field=models.CharField(max_length=555, verbose_name='Описание'),
        ),
    ]
