# Generated by Django 4.2.7 on 2023-12-04 06:56

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', django_quill.fields.QuillField()),
                ('salery_min', models.FloatField(default=0)),
                ('salery_max', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkAbroadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('work_abroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_abroad.workabroad')),
            ],
        ),
    ]
