# Generated by Django 5.0 on 2023-12-26 10:34

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_abroad', '0002_alter_workabroadimage_work_abroad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workabroad',
            name='country',
            field=django_countries.fields.CountryField(default='RU', max_length=2),
        ),
    ]
